require("modules.autostart")
require("modules.rules")
require("modules.env")
require("modules.general")
require("modules.input")
require("modules.mics")
require("modules.decoration")
-- require("modules.animation(vertical)")
require("modules.animation(horizontal)")
require("modules.binds")
